export const environment = {
  production: true,
  API_PATH:'https://api-saraswati-coding-club.herokuapp.com',
  // API_PATH:'http://localhost:29842',
  problemtags:[
    'implementation',
    'math',
    'greedy',
    'dp',
    'data-structures',
    'brute-force',
    'constructive-algorithms',
    'graphs',
    'sortings',
    'binary-search',
    'dfs-and-similar',
    'trees',
    'strings',
    'number-theory',
    'combinatorics',
    'geometry',
    'bitmasks',
    'two-pointers',
    'dsu',
    'shortest-paths',
    'probabilities',
    'divide-and-conquer',
    'hashing',
    'games',
    'flows',
    'interactive',
    'matrices',
    'string suffix structures',
    'fft',
    'graph-matchings',
    'ternary-search',
    'expression-parsing',
    'meet-in-the-middle',
    '2-sat',
    'chinese-remainder-theorem',
    'schedules'
  ]
};